#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="${1:-$ROOT_DIR/KEYMAPS_RUNTIME.md}"

TMP_LUA="$(mktemp)"
trap 'rm -f "$TMP_LUA"' EXIT

cat > "$TMP_LUA" <<'LUA'
local out = vim.env.KEYMAPS_OUT
if not out or out == "" then
  error("KEYMAPS_OUT is not set")
end

local function esc(s)
  s = tostring(s or "")
  if s:sub(1, 1) == " " then
    s = "<leader>" .. s:sub(2)
  end
  s = s:gsub("\n", " ")
  s = s:gsub("|", "\\|")
  return s
end

local mode_names = {
  n = "Normal",
  i = "Insert",
  x = "Visual",
  s = "Select",
  o = "Operator-pending",
  t = "Terminal",
  c = "Command",
}

local modes = { "n", "i", "x", "s", "o", "t", "c" }
local lines = {}

lines[#lines + 1] = "## Neovim Runtime Keymaps"
lines[#lines + 1] = ""
lines[#lines + 1] = "> Generated by `scripts/export-keymaps.sh`"
lines[#lines + 1] = ""
lines[#lines + 1] = "Only mappings with non-empty `desc` are included."

for _, mode in ipairs(modes) do
  local maps = vim.api.nvim_get_keymap(mode)
  local filtered = {}

  for _, m in ipairs(maps) do
    if m.desc and m.desc ~= "" then
      filtered[#filtered + 1] = m
    end
  end

  table.sort(filtered, function(a, b)
    if a.lhs == b.lhs then
      return (a.desc or "") < (b.desc or "")
    end
    return a.lhs < b.lhs
  end)

  if #filtered > 0 then
    lines[#lines + 1] = ""
    lines[#lines + 1] = "### " .. mode_names[mode] .. " (`" .. mode .. "`)"
    lines[#lines + 1] = ""
    lines[#lines + 1] = "| Key | Description | Action | Flags |"
    lines[#lines + 1] = "|---|---|---|---|"

    for _, m in ipairs(filtered) do
      local action = (m.rhs and m.rhs ~= "") and ("`" .. esc(m.rhs) .. "`") or "`<Lua callback>`"
      local flags = {}
      if m.expr == 1 then flags[#flags + 1] = "expr" end
      if m.noremap == 0 then flags[#flags + 1] = "remap" end
      if m.silent == 1 then flags[#flags + 1] = "silent" end
      if m.nowait == 1 then flags[#flags + 1] = "nowait" end
      local flags_s = #flags > 0 and table.concat(flags, ", ") or "-"

      lines[#lines + 1] = string.format(
        "| `%s` | %s | %s | %s |",
        esc(m.lhs),
        esc(m.desc),
        action,
        flags_s
      )
    end
  end
end

vim.fn.writefile(lines, out)
LUA

XDG_CACHE_HOME="${XDG_CACHE_HOME:-/tmp}" KEYMAPS_OUT="$OUT_FILE" nvim --headless -i NONE -u "$ROOT_DIR/init.lua" -c "luafile $TMP_LUA" -c "qa!"

printf 'Exported keymaps to %s\n' "$OUT_FILE"
